# Generated by Django 4.2.7 on 2024-05-19 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('conductor', 'conductor')], default='user', max_length=10),
        ),
    ]
