# Generated by Django 4.2.7 on 2024-05-20 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='numtelefonico',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
